### ISSUE TITLE
Fix sync from wos script

### ISSUE THREAD

**Issue by jackbravo** [wizeline/project-lab#312]
This is making our [deploys](https://github.com/wizeline/project-lab/runs/6294870596?check_suite_focus=true) to development fail.

Probably changing the skills deleteMany query to a raw query could help, based on the last comment.

```
/home/runner/work/project-lab/project-lab/node_modules/@prisma/client/runtime/index.js:45629
        throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
              ^
Error: Query parameter limit exceeded error: Parameter limits for this database provider require this query to be split into multiple queries, but the negation filters used prevent the query from being split. Please reduce the used values in the query..
    at Object.request (/home/runner/work/project-lab/project-lab/node_modules/@prisma/client/runtime/index.js:45629:15)
    at PrismaClient._request (/home/runner/work/project-lab/project-lab/node_modules/@prisma/client/runtime/index.js:46456:18)
    at async Promise.all (index 0)
    at Object.syncCatalogs [as default] (/home/runner/work/project-lab/project-lab/tasks/syncAllDataFromWOS.ts:75:3)
    at task (/home/runner/work/project-lab/project-lab/tasks/syncAllDataFromWOSTask.ts:13:3)
```

**Comment by jackbravo** [comment]
These are the same errors but in local, that @leonardohervert [found](https://wizeline.slack.com/archives/CQCB5MWG6/p1651690777512519)

![image](https://user-images.githubusercontent.com/15214/166956711-8446843f-40e4-4c7e-bc55-73e2816e13b5.png)
